// <auto-generated />
namespace BB.Presentation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Pages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Pages));
        
        string IMigrationMetadata.Id
        {
            get { return "201704202126287_Pages"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
